<Project Sdk="Microsoft.NET.Sdk"><PropertyGroup><AssemblyName>Olga.Core.Application</AssemblyName></PropertyGroup><ItemGroup><ProjectReference Include="..\Olga.Core.Domain\Olga.Core.Domain.csproj" /><ProjectReference Include="..\Olga.Core.Contracts\Olga.Core.Contracts.csproj" /></ItemGroup></Project>
