<Project Sdk="Microsoft.NET.Sdk"><PropertyGroup><AssemblyName>Olga.Core.Infrastructure</AssemblyName></PropertyGroup><ItemGroup><ProjectReference Include="..\Olga.Core.Application\Olga.Core.Application.csproj" /><PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="10.0.3" /><PackageReference Include="EFCore.NamingConventions" Version="10.0.1" /><PackageReference Include="Microsoft.EntityFrameworkCore.Relational" Version="10.0.12" /><PackageReference Include="Microsoft.EntityFrameworkCore.InMemory" Version="10.0.12" /><PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.12"><PrivateAssets>all</PrivateAssets></PackageReference></ItemGroup></Project>
