<Project Sdk="Microsoft.NET.Sdk"><PropertyGroup><AssemblyName>Olga.Core.Infrastructure</AssemblyName></PropertyGroup><ItemGroup><ProjectReference Include="..\Olga.Core.Application\Olga.Core.Application.csproj" /><PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="10.0.11" /><PackageReference Include="Microsoft.EntityFrameworkCore.InMemory" Version="10.0.11" /><PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.11"><PrivateAssets>all</PrivateAssets></PackageReference></ItemGroup></Project>
